server:
  port: 9090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keyclock:
            client-id: spring-boot-client
            client-secret: _GfIfvgOUsPhn73SRu6eDIX_pkd6Vdyp2yesnOjl
            authorization-grant-type: authorization_code
            client-name: spring-boot-client
            scope: openid
            redirectUri: http://localhost:9090/oauth/login/client-app
        provider:
          keyclock:
            authorization-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs

#messages:
#  base-uri: http://localhost:8092/messages